### ISSUE TITLE
Options to hide breadcrumb for rem references

### ISSUE THREAD

**Issue by Shomvel** [remnoteio/remnote-issues#1076]
<img width="196" alt="Screen Shot 2021-03-31 at 14 26 18" src="https://user-images.githubusercontent.com/7360051/113099763-10532480-922d-11eb-87c5-d848f9f0d6cc.png">

If a rem is nested deep inside other rems, referring to it results in breadcrumbs, which makes the sentence hard to read. I hope there would be an option in settings to toggle this behavior.

**Comment by 5eagull** [comment]
CSS to hide breadcrumbs
```css
/* 隐藏面包屑 */
.rem-reference.button.rem-reference-link .gray {    
    display : none; 
}
.rem-reference.button.rem-reference-link .join-arrow {    
    display : none; 
}
```
