### ISSUE TITLE
Latex Editor overlaps higher formulas like matrix

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#1095]
**Describe the bug**
It seems like the latex editor only expects a single line of rendered latex.
When the rendered latex has multiple lines, e.g. from this input:

```
\begin{matrix}
 x & y \\
 z & w
\end{matrix}
```

it looks like this:

![image](https://user-images.githubusercontent.com/4137110/113516454-9f887100-957a-11eb-8c6d-fb8a2c4c6d79.png)

I'd expect the latex editor popup to be pinned exactly to the bottom of the rendered latex output at all times like this
![image](https://user-images.githubusercontent.com/4137110/113516498-dc546800-957a-11eb-8b42-e5dcd695b733.png)

I think this can be fixed with this CSS, but I'm not 100% sure there are no side effects:

```css
.latex-node__tex--focused-inline, .katex, .katex-html {
  display: inline-block;
}
```
