### ISSUE TITLE
Code blocks shake on hover

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#245]
The height of empty lines changes on hover. An extra space in these lines prevents the problem.
Related: #139 for LateX

![remnote-bug-code-shake-newline](https://user-images.githubusercontent.com/4137110/97683801-c9ec7480-1a98-11eb-8bb7-4656213456bd.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 85

Note: I don't know what the plan for code editing in RemNote is. Maybe you will integrate the monaco editor (as a plugin) at some point anyway.

**Comment by zhanghanduo** [comment]
This issue has been around with latex equations and portals, as shown in issue#72.
> https://github.com/remnoteio/remnote-issues/issues/72#issuecomment-688545168

I am also troubled like you.

**Comment by hannesfrank** [comment]
Here is a quick fix. If you don't want to include it in the default style sheet I'll happily make a 📜 for it 😛 

```css
#code-node .codeLine:after {
  content: " ";
  visibility: hidden;
}

#code-node {
  display: inline-block;
  text-decoration: none;
}
```
