### ISSUE TITLE
Clicking in code block sets cursor wrong

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#247]
I can't reproduce this reliably. Here is a troublesome code block you can try:

```css
.rem[data-rem-tags~=rainbow] {
  background: linear-gradient(to right, red,orange,yellow,green,blue,indigo,violet,red);
  background-repeat:repeat-x;
  animation: go 3s forwards linear infinite;
  background-size: 50% auto;
}

@keyframes go {
  from {background-position: top left;
}
```

![remnote-bug-code-cursor](https://user-images.githubusercontent.com/4137110/97688651-b510e080-1a9a-11eb-9562-1d19545185b8.gif)

(There is an additional issue shown at the beginning where an extra empty line appears when not hovered.)

On some lines, clicking after a line sets the cursor to the beginning of the next line. When navigating with left/right arrows on such a line I also have to press an additional time at the beginning of the line just like if there was a zero width space. I am pretty sure though there is none. I copied the code to a text editor, checked there was none and copied it back into a new code block.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome 85
