### ISSUE TITLE
Add href as attribute for .rich-text-editor .LinkNode

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#407]
I want to show the URL of a `.LinkNode` on hover. There is a `data-for` attribute I can use, but it is prefixed with `link`. Could you please add another data attribute like `data-href` or just `href` or remove the prefix of `data-for`?

Here is the css I'd like to work:
```css
.LinkNode:hover::after {
  content: attr(data-for);
  position: absolute;
  text-align: center;
  max-width: 21em;
  overflow: hidden;
  text-overflow: ellipsis;
  
  bottom: 100%;
  left: 50%;
  transform: translate(-50%, 50%) scale(0.5);
  
  font-size: 0.8em;
  color: black;
  background-color: whitesmoke;
  border: 1px solid grey;
  padding: 3px 5px;
  border-radius: 3px;
  
  animation: linknode-href-tooltip 60ms ease-out forwards;
}

@keyframes linknode-href-tooltip {
  to {
    transform: translate(-50%, 0);
  }
}
```

Here is how it would look like:
![image](https://user-images.githubusercontent.com/4137110/102205681-ce93ad80-3ecb-11eb-95e7-80c5e9bda6b4.png)

Rationale is that there is currently no way to show the URL on the desktop app since it does not have a link preview in the bottom left corner like a browser.
