### ISSUE TITLE
Checkbox position in page titles

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#702]
Checkboxes in page titles are not positioned properly.
![image](https://user-images.githubusercontent.com/4137110/106587857-6ae04500-654a-11eb-9699-1dcf4eb67704.png)

Checkboxes for H1 etc. are also slightly off.
This is what I have in my Custom CSS now. (My non-CSS-expert intuition is that float+margin-top make layouts harder?)

```css
.rem-checkbox {
  float: unset !important;
  margin-top: unset !important;
  vertical-align: middle;
}

/* These are required because focusing a rem adds extra div wrappers. */
.rem-checkbox + div,
.rem-checkbox + div > div,
.rem-checkbox + div > div > div {
  display: inline;
}

/* Also center power up icon */
#DocumentTitle .rem-is-custom-rem-type {
  float: unset !important;
}

/* Fine tune for headers. This seems to also make top and bottom space visually the same for latin characters. */
.rem-header--1,
.rem-header--2,
.rem-header--3 {
  padding-top: 1.5px !important;
}
```

I'm not sure if `display: inline` breaks something else. At first glance it seems not to be the case.

After:
![image](https://user-images.githubusercontent.com/4137110/106587810-5f8d1980-654a-11eb-9d3b-f013f25d858c.png)

(Same thing applies to bullet points but they seem much better fine-tuned 👍 .)
